name: Deploy to GitHub Pages

on:
  push:
    # AHORA SE ACTIVA CUANDO HAY UN PUSH A LA RAMA MASTER
    branches: [master]
  
  # Permite ejecutar el flujo de trabajo manualmente desde la pestaña de Actions
  workflow_dispatch:

# Permisos requeridos para que GitHub Pages pueda desplegar
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Instala las dependencias y genera la carpeta 'build'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        # Asumo que usas yarn, si usas npm, cambia el comando a 'npm ci' o 'npm install'
        run: yarn install --frozen-lockfile

      - name: Build website
        run: yarn build # Si usas npm: 'npm run build'

      # Prepara la carpeta 'build' para el despliegue
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      # Despliega a GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4